# Generated by Django 2.2.5 on 2019-11-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='phno',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
