# Generated by Django 2.2.5 on 2019-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbook', '0002_userprofileinfo_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bloodgrp',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
