# Generated by Django 2.2.5 on 2019-11-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbook', '0003_userprofileinfo_bloodgrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='bloodgrp',
            new_name='BloodGroup',
        ),
    ]
